#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  target_command=""
  target_key=""
  target_value=""
  color=""
  quiet=""
}

_requirements() {
  local \
    _app
  _check_cmd \
    'displayctl'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/$( \
    _get \
      "app" \
      "name")"
  echo \
    "${_dir}"
}

_powerctl() {
  local \
    _command="${1}" \
    _cmd \
    _args=() \
    _app \
    _db
  if [[ "${_command}" == "get" ]]; then
    _cmd="_power_key_value_${_command}"
    _args+=(
      "$( \
        _get \
          "target" \
          "key")"
      )
  elif [[ "${_command}" == "set" ]]; then
    _cmd="_power_key_value_${_command}"
    _args+=(
      "$( \
        _get \
          "target" \
          "key")"
      "$( \
        _get \
          "target" \
          "value")"
    )
  else
    _msg_error \
      "command ${_command} not existing"
  fi
  "${_cmd}" \
    "${_args[@]}"
}

# Set power key option
_power_key_value_set() {
  local \
    _key="${1}" \
    _value="${2}" \
    _power_mode \
    _display_scale
  _msg_info \
    "Setting value ${_value} for key ${_key}"
  if [[ "${_key}" == "mode" ]]; then
    _power_mode="$( \
      _power_key_value_get \
        "${_key}")"
    if [[ "${_power_mode}" == "${_value}" ]]; then
      msg_info \
        "value '${_value}' already set"
    elif [[ "${_power_mode}" != "${_value}" ]]; then
      if [[ "${_value}" == "powersaving" ]]; then
        _display_scale="0.66666"
      elif [[ "${_value}" == "normal" ]]; then
        _display_scale="1"
      fi
      displayctl \
        set \
        "scale" \
        "${_display_scale}"
    fi
  fi
}

# Get power settings key
# $1: target settings key
_power_key_value_get() {
  local \
    _key="${1}" \
    _display_scale
  if [[ "${_key}" == "mode" ]]; then
    _display_scale="$( \
      displayctl \
        "get" \
        "scale")"
    if (( $( echo "${_display_scale} < 0.7" | bc) )); then
      echo \
        "powersaving"
    elif (( $( echo "${_display_scale} - 1 < 0.01" |bc) )); then
      echo \
        "normal"
    else
      echo \
        "${_display_scale}"
    fi
  else
    _msg_error \
      "No key ${_key}"
  fi
}

_set_overrides() {
  _set_override \
    "target" \
    "command" \
    "get"
  _set_override \
    "target" \
    "key" \
    "mode"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Manage power usage
usage:
  $(_get "app" "name")
    [options]
    <command>
    <key>
    (<value>)
  commands:
     get                  Get configuration value
       <key>
     set                  Set configuration value
       <key>
       <value>
  keys:
    mode                  Can be 'normal' or 'powersaving'
  options:
     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  local \
    _get_date
  TZ=UTC \
    printf \
      -v _get_date \
      '%(%FT%R%z)T' \
      "${SOURCE_DATE_EPOCH}"
  _msg_info "${app_name} configuration"
  _msg_info "           Operation date:   $(_get "_get" "date")"
  _msg_info "           Target command:   $(_get "target" "command")"
  _msg_info "               Target key:   $(_get "target" "key")"
  _msg_info "             Target value:   $(_get "target" "value")"
}

_globals
_global_variables
_requirements
_config_user_init \
  "$(_get \
       "app" \
       "name")"
# shellcheck disable=SC2034
while \
  getopts \
    'cvh?' \
    arg; do
  case \
    "${arg}" in
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg_error \
    "no command given" \
    0
  _set_overrides
  _usage \
    1
fi
_set \
  "target" \
  "command" \
  "${1}"
if (( 1 < $# )); then
  _set \
    "target" \
    "key" \
    "${2}"
fi
if (( 2 < $# )); then
  _set \
    "target" \
    "value" \
    "${3}"
fi
_set_overrides
_config_user_init \
  "$( \
    _get \
      "app" \
      "name")"
_show_config
app_opts=(
  "$( \
    _get \
      "target" \
      "command")"
)
_powerctl \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
